# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-650dab1e-fd76-4267-9375-cd9fbb24bc1a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-650dab1e-fd76-4267-9375-cd9fbb24bc1a".device = "/dev/disk/by-uuid/650dab1e-fd76-4267-9375-cd9fbb24bc1a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3153-7272";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/media/SSD" =
    { device = "/dev/disk/by-uuid/d44c0230-74e7-4360-854b-8bc22a364289";
      fsType = "ext4";
    };


  swapDevices =
    [ { device = "/dev/mapper/luks-bca35ad9-6287-404a-92e4-1ff16e0b5a43"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
