# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-4017bf27-d01f-4e44-9ff1-2c3bceea7677";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4017bf27-d01f-4e44-9ff1-2c3bceea7677".device = "/dev/disk/by-uuid/4017bf27-d01f-4e44-9ff1-2c3bceea7677";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B618-50A4";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-a947baab-bcc2-466e-930f-bb42f014bd85";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a947baab-bcc2-466e-930f-bb42f014bd85".device = "/dev/disk/by-uuid/a947baab-bcc2-466e-930f-bb42f014bd85";

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
