# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-ce97d914-df06-47e5-99f4-ea169de744bf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-ce97d914-df06-47e5-99f4-ea169de744bf".device = "/dev/disk/by-uuid/ce97d914-df06-47e5-99f4-ea169de744bf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D3D5-BC58";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-210e7ec8-1c1e-4139-86aa-aebe4cc30b62";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-210e7ec8-1c1e-4139-86aa-aebe4cc30b62".device = "/dev/disk/by-uuid/210e7ec8-1c1e-4139-86aa-aebe4cc30b62";

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
